# Generated by Django 4.1.7 on 2023-03-26 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course_image', models.CharField(max_length=255)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video1', models.CharField(max_length=255)),
                ('title1', models.CharField(max_length=255)),
                ('video2', models.CharField(blank=True, max_length=255, null=True)),
                ('title2', models.CharField(blank=True, max_length=255, null=True)),
                ('video3', models.CharField(blank=True, max_length=255, null=True)),
                ('title3', models.CharField(blank=True, max_length=255, null=True)),
                ('video4', models.CharField(blank=True, max_length=255, null=True)),
                ('title4', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachme.course')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.CharField(max_length=255)),
                ('text1', models.CharField(max_length=255)),
                ('img2', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.CharField(blank=True, max_length=255, null=True)),
                ('img3', models.CharField(blank=True, max_length=255, null=True)),
                ('text3', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='teachme.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='story_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachme.story'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255, verbose_name='Answer Text')),
                ('is_right', models.BooleanField(default=False)),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer', to='teachme.question')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
