# Generated by Django 4.1.7 on 2023-04-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='audio_link',
        ),
        migrations.RemoveField(
            model_name='story',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='story',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='story',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='story',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='story',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='story',
            name='text3',
        ),
        migrations.AddField(
            model_name='story',
            name='story_name',
            field=models.CharField(default='story_name', max_length=255),
        ),
        migrations.AddField(
            model_name='story',
            name='video',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
