# Generated by Django 4.1.7 on 2023-04-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachme', '0002_remove_story_audio_link_remove_story_img1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='video',
            field=models.CharField(default='video_link', max_length=255),
        ),
    ]
