# Generated by Django 4.1.7 on 2023-04-13 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachme', '0003_alter_story_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='story_post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachme.story'),
        ),
    ]
