# Generated by Django 4.1.7 on 2023-04-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachme', '0004_alter_post_story_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Lesson',
        ),
    ]
