# Generated by Django 4.1.7 on 2023-05-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachme', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
